trigger:
- master
- features/*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 2.x SDK for testing'
    inputs:
      packageType: 'sdk'
      version: '2.x'
  - task: UseDotNet@2
    displayName: 'Install main .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: Bash@3
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.sh

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 2.x SDK for testing'
    inputs:
      packageType: 'sdk'
      version: '2.x'
  - task: UseDotNet@2
    displayName: 'Install main .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: BatchScript@1
    inputs:
      filename: './build.cmd'
  - task: NuGetCommand@2
    displayName: 'Push package to Github'
    inputs:
      command: push
      packagesToPush: 'artifacts/*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: 'GitHub Packages'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))